name: Nightly Build

on:
  schedule:
    # - cron: "0 0 * * *"
    - cron: "45 21 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow
  # push: # Trigger on any commit to any branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      # Add PostgreSQL service
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: bookly
        ports:
          - 5432:5432

      # Add Redis service
      redis:
        image: redis:6
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov
          pip install celery

      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Login to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bookly:nightly
            ghcr.io/${{ github.repository_owner }}/bookly:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send Notification
        if: always()
        run: |
          python -m src.notify \
            --subject "Nightly Build Failed" \
            --body "The nightly build failed. Please check the logs for more information." \
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
