name: PR Title Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        id: check-title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PATTERN="^(feat|fix|docs|style|refactor|test|chore)(\([a-z-]+\))?: .+"

          if [[ ! "$PR_TITLE" =~ $PATTERN ]]; then
            echo "PR title '$PR_TITLE' does not follow conventional commit format"
            echo "failed=true" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Close PR and Send Notification
        if: failure()
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "PR is being closed because the title does not follow the Conventional Commits specification. Please rename your PR to follow the format: type(scope): description"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
