name: PR Title Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check PR Title
        id: check-title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PATTERN="^(feat|fix|docs|style|refactor|test|chore)(\([a-z-]+\))?: .+"

          if [[ ! "$PR_TITLE" =~ $PATTERN ]]; then
            echo "PR title '$PR_TITLE' does not follow conventional commit format"
            echo "failed=true" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Check Commit Messages
        id: check-commits
        run: |
          # Get all commits in the PR 
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch

          COMMITS=$(git log --format=%s origin/${{ github.event.pull_request_base.ref }}..pr-branch)

          # Initialize variables
          FAILED=false
          INVALID_COMMITS=""

          PATTERN="^(feat|fix|docs|style|refactor|test|chore)(\([a-z-]+\))?: .+"

          while IFS= read -r COMMIT; do
            if [[ ! -z "$commit" ]] && [[ ! "$COMMIT" =~ $PATTERN ]]; then
              FAILED=true
              INVALID_COMMITS="$INVALID_COMMITS\n$COMMIT"
            fi
          done <<< "$COMMITS"

          if [ "$FAILED" = true ] then 
            echo "Invalid commits found:"
            echo -e "$INVALID_COMMITS"
            echo "invalid_commits<<EOF" >> $GITHUB_OUTPUT
            echo -e "$INVALID_COMMITS" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit
          fi

      - name: Close PR and Send Notification
        if: failure()
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "PR is being closed because the title does not follow the Conventional Commits specification. Please rename your PR to follow the format: type(scope): description"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
